project_id = "ydvmulhmmragakuimuqm"

[functions.scrape-jobs]
verify_jwt = false

[functions.send-contact-email]
verify_jwt = false

[functions.create-checkout]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.export-saved-jobs]
verify_jwt = true
